### ISSUE TITLE
More efficient way to download model weights

### ISSUE THREAD

**Issue by kyancey** [ArmastusChen/inverse_painting#2]
I appreciate you guys making the code and weights available. I really look forward to getting it running.

However, putting the weights in a Google Drive folder is less than ideal. I would wager a lot of people running this are doing so on a remote server instance like runpod. It's really hard to download stuff from Google Drive on a command line, even with tools like gdown. Trust me. I've tried.

The alternative is to download all the files from Google Drive and then upload them again. That's a lot of uploading and downloading. It's also hard because you have to download files individually and recreate the folder structure. Trying to download the entire folder doesn't work. Google Drive can't zip together that much content, so you end up with many disparate download zip files interspersed with unzipped content. The structure of the folders is lost, and you're left trying to piece everything together.

It would be nice if these files were in one large archive file that could be untarred or unzipped.

**Comment by ArmastusChen** [comment]
Hi @kyancey ,

Thanks for your interest and suggestions! I have uploaded the .zip file on google drive. I also keep the previous folders in case anyone wants to download a specific model. 

https://drive.google.com/drive/folders/1exu6Ws-NIZO-3qNO5s50b71fSQALkdvK

Cheers

**Comment by ArmastusChen** [comment]
I have updated the readme with command to download from Huggingface. You can use the following commands. It should be much easier now.

git lfs install
git clone https://huggingface.co/boweiche/inverse_painting
