### ISSUE TITLE
Downloading models from Google Drive painful exercise

### ISSUE THREAD

**Issue by robertor4** [ArmastusChen/inverse_painting#3]
I'm getting errors downloading the files from Google Drive, also due to the size. Zipping via web console doesn't work well, unable to download.

Also on a machine itself, "gdown" is unable to download all the files in the folder, even with --no-cookie and --continue flags.

The folder also includes the .git (hidden) folders - which are unnecessary.

Is there another way you can make this available?

**Comment by ArmastusChen** [comment]
I have updated the readme with command to download from Huggingface. You can use the following commands. It should be much easier now. 

  git lfs install
  git clone https://huggingface.co/boweiche/inverse_painting

**Comment by robertor4** [comment]
Ah, great! That is indeed much easier. Thanks.

I'd recommend to use "lfs" for more efficient cloning:

`git lfs clone https://huggingface.co/boweiche/inverse_painting`

**Comment by ArmastusChen** [comment]
Cool, I am closing this issue because the it is solved.
