### ISSUE TITLE
Unable to install requirements.txt on WIN10

### ISSUE THREAD

**Issue by sanasigma** [ArmastusChen/inverse_painting#4]
(inverse_painting) D:\inverse_painting>pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch==2.1.2
  Using cached https://download.pytorch.org/whl/cu118/torch-2.1.2%2Bcu118-cp310-cp310-win_amd64.whl (2722.7 MB)
Collecting torchvision==0.16.2
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.16.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting filelock (from torch==2.1.2)
  Using cached https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting typing-extensions (from torch==2.1.2)
  Using cached https://download.pytorch.org/whl/typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting sympy (from torch==2.1.2)
  Using cached https://download.pytorch.org/whl/sympy-1.13.1-py3-none-any.whl (6.2 MB)
Collecting networkx (from torch==2.1.2)
  Using cached https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting jinja2 (from torch==2.1.2)
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.3-py3-none-any.whl (133 kB)
Collecting fsspec (from torch==2.1.2)
  Using cached https://download.pytorch.org/whl/fsspec-2024.2.0-py3-none-any.whl (170 kB)
Collecting numpy (from torchvision==0.16.2)
  Using cached https://download.pytorch.org/whl/numpy-1.26.3-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting requests (from torchvision==0.16.2)
  Using cached https://download.pytorch.org/whl/requests-2.28.1-py3-none-any.whl (62 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision==0.16.2)
  Using cached https://download.pytorch.org/whl/pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.1.2)
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Collecting charset-normalizer<3,>=2 (from requests->torchvision==0.16.2)
  Using cached https://download.pytorch.org/whl/charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5 (from requests->torchvision==0.16.2)
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1 (from requests->torchvision==0.16.2)
  Using cached https://download.pytorch.org/whl/urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17 (from requests->torchvision==0.16.2)
  Using cached https://download.pytorch.org/whl/certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.1.2)
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
Successfully installed MarkupSafe-2.1.5 certifi-2022.12.7 charset-normalizer-2.1.1 filelock-3.13.1 fsspec-2024.2.0 idna-3.4 jinja2-3.1.3 mpmath-1.3.0 networkx-3.2.1 numpy-1.26.3 pillow-10.2.0 requests-2.28.1 sympy-1.13.1 torch-2.1.2+cu118 torchvision-0.16.2+cu118 typing-extensions-4.9.0 urllib3-1.26.13

(inverse_painting) D:\inverse_painting>pip install -r requirements.txt
Collecting absl-py==2.1.0 (from -r requirements.txt (line 1))
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting accelerate==0.21.0 (from -r requirements.txt (line 2))
  Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
Collecting aiofiles==23.2.1 (from -r requirements.txt (line 3))
  Using cached aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Collecting altair==5.2.0 (from -r requirements.txt (line 4))
  Using cached altair-5.2.0-py3-none-any.whl.metadata (8.7 kB)
Collecting annotated-types==0.6.0 (from -r requirements.txt (line 5))
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting antlr4-python3-runtime==4.9.3 (from -r requirements.txt (line 6))
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Collecting anyio==4.3.0 (from -r requirements.txt (line 7))
  Using cached anyio-4.3.0-py3-none-any.whl.metadata (4.6 kB)
Collecting appdirs==1.4.4 (from -r requirements.txt (line 8))
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting attrs==23.2.0 (from -r requirements.txt (line 9))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 10))
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bitsandbytes==0.42.0 (from -r requirements.txt (line 11))
  Using cached bitsandbytes-0.42.0-py3-none-any.whl.metadata (9.9 kB)
Collecting certifi==2024.2.2 (from -r requirements.txt (line 12))
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 13))
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl.metadata (34 kB)
Collecting click==8.1.7 (from -r requirements.txt (line 14))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting clip==0.2.0 (from -r requirements.txt (line 15))
  Using cached clip-0.2.0.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
Collecting clip-anytorch==2.5.2 (from -r requirements.txt (line 16))
  Using cached clip_anytorch-2.5.2-py3-none-any.whl.metadata (8.1 kB)
Collecting color-matcher==0.5.0 (from -r requirements.txt (line 17))
  Using cached color_matcher-0.5.0-py3-none-any.whl.metadata (1.3 kB)
Collecting colorama==0.4.6 (from -r requirements.txt (line 18))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting colour==0.1.5 (from -r requirements.txt (line 19))
  Using cached colour-0.1.5-py2.py3-none-any.whl.metadata (18 kB)
Collecting contourpy==1.2.0 (from -r requirements.txt (line 20))
  Using cached contourpy-1.2.0-cp310-cp310-win_amd64.whl.metadata (5.8 kB)
Collecting cycler==0.12.1 (from -r requirements.txt (line 21))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting ddt==1.7.2 (from -r requirements.txt (line 22))
  Using cached ddt-1.7.2-py2.py3-none-any.whl.metadata (832 bytes)
Collecting deepspeed==0.12.6 (from -r requirements.txt (line 23))
  Using cached deepspeed-0.12.6.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\OP\AppData\Local\Temp\pip-install-hokvfip0\deepspeed_5c783ad191924754b462af062bf29ecb\setup.py", line 182, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\OP\AppData\Local\Temp\pip-install-hokvfip0\deepspeed_5c783ad191924754b462af062bf29ecb\setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(inverse_painting) D:\inverse_painting>

![image](https://github.com/user-attachments/assets/53a8bc32-09f3-4232-96ba-79953d215f09)

**Comment by ArmastusChen** [comment]
We only test the code on Ubuntu. The error you're encountering appears to stem from the installation of the DeepSpeed package.

Please note that DeepSpeed is required only for training. If you only wish to run the inference (demo) code, installing DeepSpeed is not necessary. However, if you plan to perform training, you can refer to the following link for guidance on installing DeepSpeed on Windows.


https://github.com/microsoft/DeepSpeed/issues/4729

**Comment by sanasigma** [comment]
Thank you! I just wanted to try the demo.
